import { describe, expect, it } from '@jest/globals';
import { buildEnterpriseReportsMetrics } from '@/utils/enterprise-metrics';
import type { PaymentWithChit } from '@/utils/payment-month';

describe('buildEnterpriseReportsMetrics', () => {
  it('recalculates member analytics using chit payout summaries', () => {
    const payments = [
      {
        id: 'a1',
        chit_id: 'withdrawn-chit',
        installment_no: 1,
        expected_amount: 5000,
        maturity_amount: 73800,
        amount_paid: 5000,
        advance_amount_paid: 5000,
        status: 'paid',
        paid_date: '2026-05-01',
        payment_mode: null,
        paid_to: null,
        created_at: '',
        updated_at: '',
        chit: {
          id: 'withdrawn-chit',
          type: 'ONE_LAKH',
          category: '5th',
          start_date: '2026-01-01',
          person: { name: 'Alpha', city: 'Chennai' },
        },
      },
      {
        id: 'a2',
        chit_id: 'active-chit',
        installment_no: 1,
        expected_amount: 2500,
        maturity_amount: 36900,
        amount_paid: 2500,
        advance_amount_paid: 2500,
        status: 'paid',
        paid_date: '2026-05-02',
        payment_mode: null,
        paid_to: null,
        created_at: '',
        updated_at: '',
        chit: {
          id: 'active-chit',
          type: 'FIFTY_THOUSAND',
          category: '10th',
          start_date: '2026-02-01',
          person: { name: 'Alpha', city: 'Chennai' },
        },
      },
      {
        id: 'a3',
        chit_id: 'active-chit',
        installment_no: 2,
        expected_amount: 2000,
        maturity_amount: 37500,
        amount_paid: 0,
        advance_amount_paid: 0,
        status: 'pending',
        paid_date: null,
        payment_mode: null,
        paid_to: null,
        created_at: '',
        updated_at: '',
        chit: {
          id: 'active-chit',
          type: 'FIFTY_THOUSAND',
          category: '10th',
          start_date: '2026-02-01',
          person: { name: 'Alpha', city: 'Chennai' },
        },
      },
      {
        id: 'b1',
        chit_id: 'beta-chit',
        installment_no: 1,
        expected_amount: 5000,
        maturity_amount: 73800,
        amount_paid: 5000,
        advance_amount_paid: 5000,
        status: 'paid',
        paid_date: '2026-05-03',
        payment_mode: null,
        paid_to: null,
        created_at: '',
        updated_at: '',
        chit: {
          id: 'beta-chit',
          type: 'ONE_LAKH',
          category: '5th',
          start_date: '2026-03-01',
          person: { name: 'Beta', city: 'Madurai' },
        },
      },
    ] as PaymentWithChit[];

    const metrics = buildEnterpriseReportsMetrics({
      payments,
      chits: [
        {
          id: 'withdrawn-chit',
          person_id: 'person-alpha',
          type: 'ONE_LAKH',
          category: '5th',
          start_date: '2026-01-01',
          end_date: '2027-08-01',
          matured: false,
          withdrawal: true,
          withdrawal_date: '2026-05-10',
          withdrawal_net_amount: 74000,
          collection_variance: 200,
          person: { name: 'Alpha', city: 'Chennai' },
        },
        {
          id: 'active-chit',
          person_id: 'person-alpha',
          type: 'FIFTY_THOUSAND',
          category: '10th',
          start_date: '2026-02-01',
          end_date: '2027-09-01',
          matured: false,
          withdrawal: false,
          withdrawal_date: null,
          withdrawal_net_amount: null,
          collection_variance: null,
          person: { name: 'Alpha', city: 'Chennai' },
        },
        {
          id: 'beta-chit',
          person_id: 'person-beta',
          type: 'ONE_LAKH',
          category: '5th',
          start_date: '2026-03-01',
          end_date: '2027-10-01',
          matured: false,
          withdrawal: false,
          withdrawal_date: null,
          withdrawal_net_amount: null,
          collection_variance: null,
          person: { name: 'Beta', city: 'Madurai' },
        },
      ],
      loans: [],
      repayments: [],
    });

    expect(metrics.memberRevenue[0]).toMatchObject({
      personId: 'person-alpha',
      member: 'Alpha',
      city: 'Chennai',
      chits: 2,
      totalPaid: 7500,
      outstanding: 2000,
      amountReturned: 121500,
      profit: -112000,
      variance: 0,
    });
  });
});
